ALTER TABLE PRODUCT
MODIFY NAME VARCHAR2(150) ;

ALTER TABLE PRODUCT 
ADD PRICE NUMBER NOT NULL;

ALTER TABLE PURCHASE_ORDER
DROP COLUMN EXPECTED_DELIVERY_DATE;

ALTER TABLE OFFER
DROP COLUMN MINIMUM_PRICE_PURCHASED;
