ALTER TABLE PRODUCT
MODIFY NAME VARCHAR2(150) ;

ALTER TABLE PRODUCT 
ADD PRICE NUMBER NOT NULL;

ALTER TABLE PURCHASE_ORDER
DROP COLUMN EXPECTED_DELIVERY_DATE;

ALTER TABLE OFFER
DROP COLUMN MINIMUM_PRICE_PURCHASED;

ALTER TABLE ADVERTISEMENT
DROP COLUMN DISPLAY_PREFERENCE;

ALTER TABLE CUSTOMER_ORDER 
ADD SELLER_ID NUMBER NOT NULL;

ALTER TABLE CUSTOMER_ORDER 
ADD CONSTRAINT ORDER_FK2 FOREIGN KEY(SELLER_ID) REFERENCES SELLER(SELLER_ID);

ALTER TABLE PURCHASE_ORDER
ADD PAYMENT_METHOD VARCHAR2(20) NOT NULL;

ALTER TABLE CUSTOMER_ORDER
DROP COLUMN PAYMENT_METHOD;

ALTER TABLE OFFER 
DROP COLUMN MINIMUM_QUANTITY_PURCHASED;

ALTER TABLE OFFER
ADD MINIMUM_QUANTITY_PURCHASED NUMBER NOT NULL;

ALTER TABLE PRODUCT 
ADD PRICE_SET_DATE DATE 
DEFAULT TO_DATE('01/07/2020', 'DD/MM/YYYY') NOT NULL;

ALTER TABLE PRODUCT
RENAME COLUMN PRICE_SET_DATE TO LAST_UPDATE;

ALTER TABLE CUSTOMER 
MODIFY PASSWORD VARCHAR2(150);

ALTER TABLE EMPLOYEE 
MODIFY PASSWORD VARCHAR2(150);

ALTER TABLE SELLER 
MODIFY PASSWORD VARCHAR2(150);
