CREATE OR REPLACE TRIGGER PRICE_TRIGGER
BEFORE UPDATE
OF PRICE
ON PRODUCT
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO PRODUCT_HISTORY VALUES(:OLD.PRODUCT_ID, :OLD.SELLER_ID, :OLD.LAST_UPDATE, SYSDATE, :OLD.PRICE);
END;
/